 int ar[20];
int qno(int l)
{ ar[20];
int m=21,n,k=0,flag,c;
do
{
flag=0;
c=m;
m = random(20)+1;
for(n=0;n<20;n++)
{
	if(ar[n]==m)
	{flag=1;
       //	break;
       }
}
if(flag==1)
{}
else
{

ar[k]=m;
//*mm=m;
k++;
}
}while((m==c)||(flag==1));
switch(m)
{
	case 1: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The leading coffee producing State of India is?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Andhra Pradesh ");
		outtextxy(l+90,332," 2: Kerala ");
		outtextxy(50,392," 3: Karnataka ");
		outtextxy(l+90,392," 4: Tamil Nadu  ");     //c
		break;
	case 2: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Which of the following is a cold blooded animal?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Pengiun ");
		outtextxy(l+90,332," 2: Whale ");
		outtextxy(50,392," 3: Otter ");
		outtextxy(l+90,392," 4: Tortoise  ");    //b
		break;
	case 3: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The oldest mountain system of India is?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Aravallis ");
		outtextxy(l+90,332," 2: Himalayas ");
		outtextxy(50,392," 3: Shiwaliks ");
		outtextxy(l+90,392," 4: Vindhyas  ");   //c
		break;
	case 4: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Radioactivity is measured by?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Hydrometer ");
		outtextxy(l+90,332," 2: Geiger Counter ");
		outtextxy(50,392," 3: Seismometer ");
		outtextxy(l+90,392," 4: Ammeter  ");   //c
		break;
	case 5: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Tipu Sultan ruled from?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Srirangapatnam ");
		outtextxy(l+90,332," 2: Mysore ");
		outtextxy(50,392," 3: Madaras ");
		outtextxy(l+90,392," 4: Belur  "); //a
		break;
	 case 6: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The youngest mountain range in the world is?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Himalayas ");
		outtextxy(l+90,332," 2: Alps ");
		outtextxy(50,392," 3: Andes ");
		outtextxy(l+90,392," 4: Rockies  ");  //a
		break;
	  case 7: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The bats are able to fly in dark since their wings produce?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Sound Waves ");
		outtextxy(l+90,332," 2: Ultrasonic Waves ");
		outtextxy(50,392," 3: Infrared Rays ");
		outtextxy(l+90,392," 4: Ultravoilet Rays  ");//b
		break;
	  case 8: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Deficiency of Vitamin E causes?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Rickets ");
		outtextxy(l+90,332," 2: Anemia ");
		outtextxy(50,392," 3: BRei Beri ");
		outtextxy(l+90,392," 4: Sterility  ");//d
		break;
	  case 9: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Which of the following is not a badminton player?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Prakash Padukane ");
		outtextxy(l+90,332," 2: Saina Nehrwal ");
		outtextxy(50,392," 3: P Gopichand ");
		outtextxy(l+90,392," 4: Saina Mirza  ");  //d
		break;
	  case 10: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"What is the middlie name of Sachin Tendulkar?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Ravi ");
		outtextxy(l+90,332," 2: Ramesh ");
		outtextxy(50,392," 3: Rajesh");
		outtextxy(l+90,392," 4: Ramakant  ");   //b
		break;
	 case 11: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The cheif mineral product of West Bengal is?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Copper ");
		outtextxy(l+90,332," 2: Coal ");
		outtextxy(50,392," 3: Manganese ");
		outtextxy(l+90,392," 4: Dolomite  ");//b
		break;
	 case 12: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The first underground railway in India was opened in ?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Calcutta ");
		outtextxy(l+90,332," 2: Madras ");
		outtextxy(50,392," 3: Bombay ");
		outtextxy(l+90,392," 4: Bangalore  "); //a
		break;
	 case 13: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"rajasthan has rich deposit of in the district of?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Jaipur ");
		outtextxy(l+90,332," 2: Bikaner ");
		outtextxy(50,392," 3: Nagaur ");
		outtextxy(l+90,392," 4: Jhunjhunu  "); //d
		break;
	  case 14: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Which of the following is not a sea port?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Cochin ");
		outtextxy(l+90,332," 2: Paradeep ");
		outtextxy(50,392," 3: Rameshwaram ");
		outtextxy(l+90,392," 4: Vishakhapatnam  ");    //c
		break;
	 case 15: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"First railway line in India was laid in ?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: 1835 ");
		outtextxy(l+90,332," 2: 1853 ");
		outtextxy(50,392," 3: 1917");
		outtextxy(l+90,392," 4: 1923  ");    //b
		break;
	case 16: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The Indian Institute of Science is located at?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: New Delhi ");
		outtextxy(l+90,332," 2: Madras ");
		outtextxy(50,392," 3: Kharagpur ");
		outtextxy(l+90,392," 4: Bangalore  ");  //d
		break;
	 case 17: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Which city is called 'White City' of Rajasthan?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Udaipur ");
		outtextxy(l+90,332," 2: Jaipur ");
		outtextxy(50,392," 3: Jodhpur ");
		outtextxy(l+90,392," 4: None of these  ");     //a
		break;
	case 18: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"'Contours' are lines connecting places having?");
		setcolor(BLUE);
		settextstyle(8,0,1);
		outtextxy(50,332," 1: Equal temperature ");
		outtextxy(l+90,332," 2: Equal pressure ");
		outtextxy(50,392," 3: Equal rainfall ");
		outtextxy(l+90,392," 4: Equal height  ");   //b
		break;
       case 19: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"Which of the following known as the 'Forbidden City'?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Chicago ");
		outtextxy(l+90,332," 2: Imphal ");
		outtextxy(50,392," 3: Lhasa ");
		outtextxy(l+90,392," 4: Rome  ");   //a
		break;
       case 20: setcolor(15);
		settextstyle(8,0,1);
		outtextxy(40,25,"The first heavy water plant was set up at?");
		settextstyle(8,0,1);
		setcolor(BLUE);
		outtextxy(50,332," 1: Bangalore ");
		outtextxy(l+90,332," 2: Bhopal");
		outtextxy(50,392," 3: Nangal ");
		outtextxy(l+90,392," 4: Hyderabad  ");  //c
		break;
}
return m;
};